name: Package Application with Pyinstaller

on:
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  build:
    if: contains(github.event.head_commit.message, 'Release')
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Release Tag
        run: echo "RELEASE_TAG=$(echo ${GITHUB_SHA::5})" >> $GITHUB_ENV

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install pyinstaller matplotlib pyqt5 PySerial

      - name: Package Application
        run: pyinstaller src/glue_dispenser.spec

      - name: Create temp application directory
        run: mkdir -p application

      - name: Copy application to temp directory
        run: cp dist/glue_dispenser.exe application/

      - name: Copy additional files
        run: |
          cp src/glue_dispenser.spec application/
          cp src/icon.ico application/
          cp src/logo.png application/
          cp src/GCode_writer.ipynb application/
          cp README.md application/

      - name: Zip application folder
        run: powershell Compress-Archive -Path application -DestinationPath glue_dispenser.zip

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
          files: glue_dispenser.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}